name: Deploy to EC2

on:
  push:
    branches: [ main, v1_code ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 400 ssh_key.pem
        
    - name: Deploy to Instance 1
      run: |
        BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
        ssh -i ssh_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.INSTANCE_1_IP }} << EOF
          cd /home/ec2-user/api
          git fetch origin
          git checkout $BRANCH || git checkout -b $BRANCH origin/$BRANCH
          git pull origin $BRANCH || git clone -b $BRANCH https://github.com/mohamede793/analytics-ec2-backend.git . 
          export PATH=\$PATH:/usr/local/go/bin
          /usr/local/go/bin/go mod tidy
          /usr/local/go/bin/go build -o api-server main.go
          pkill -f api-server || true
          sleep 2
          nohup ./api-server > app.log 2>&1 &
          echo "✅ Deployed to instance 1 on branch $BRANCH"
        EOF
        
    - name: Deploy to Instance 2
      run: |
        BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
        ssh -i ssh_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.INSTANCE_2_IP }} << EOF
          cd /home/ec2-user/api
          git fetch origin
          git checkout $BRANCH || git checkout -b $BRANCH origin/$BRANCH
          git pull origin $BRANCH || git clone -b $BRANCH https://github.com/mohamede793/analytics-ec2-backend.git .
          export PATH=\$PATH:/usr/local/go/bin
          /usr/local/go/bin/go mod tidy
          /usr/local/go/bin/go build -o api-server main.go
          pkill -f api-server || true
          sleep 2
          nohup ./api-server > app.log 2>&1 &
          echo "✅ Deployed to instance 2 on branch $BRANCH"
        EOF

    - name: Test API
      run: |
        sleep 10
        curl -f "http://my-api-alb-527946428.us-east-1.elb.amazonaws.com/health"